import type { CaseRecord } from "@/lib/types";

export const mockCases: CaseRecord[] = [
  {
    id: "case-001",
    user_id: "demo-patient",
    patient_name: "Anita Rao",
    patient_age: 68,
    patient_country: "India",
    relationship_to_patient: "Mother",
    main_issue: "Post-hospital confusion after pneumonia admission",
    diagnosis: "Pneumonia with discharge medication changes",
    current_symptoms: "Fatigue, cough, low appetite",
    current_medications: "Azithromycin, inhaler, diabetes medications",
    timeline: "Admitted 5 days ago, discharged 2 days ago, now family is unsure which meds to continue.",
    top_questions: [
      "Which medicines should continue?",
      "What needs urgent follow-up?",
      "Are there red flags after discharge?",
    ],
    preferred_turnaround: "24-48 hours",
    status: "physician_review",
    urgency_score: 3,
    urgency_label: "Moderate",
    created_at: "2026-04-20T17:00:00.000Z",
    submitted_at: "2026-04-21T17:00:00.000Z",
    updated_at: "2026-04-22T17:00:00.000Z",
  },
  {
    id: "case-002",
    user_id: "demo-patient",
    patient_name: "Vikram Iyer",
    patient_age: 72,
    patient_country: "India",
    relationship_to_patient: "Father",
    main_issue: "Seeking a second opinion before cardiac surgery",
    diagnosis: "Severe aortic stenosis",
    current_symptoms: "Shortness of breath with exertion",
    current_medications: "Blood pressure medication, aspirin",
    timeline: "Surgery recommended locally last week; family wants a written review before proceeding.",
    top_questions: [
      "How urgent is surgery?",
      "What additional questions should we ask?",
      "What warning signs matter most?",
    ],
    preferred_turnaround: "Standard",
    status: "delivered",
    urgency_score: 4,
    urgency_label: "High",
    created_at: "2026-04-10T17:00:00.000Z",
    submitted_at: "2026-04-11T17:00:00.000Z",
    updated_at: "2026-04-14T17:00:00.000Z",
  },
];
